enable_table_row_count_monitoring: true

sync_configs:
  - type: "mongodb"
    enable: true
    source_connection: "mongodb://<source_username>:<source_password>@<source_host>:<source_port>"
    target_connection: "mongodb://<target_username>:<target_password>@<target_host>:<target_port>"
    mongodb_resume_token_path: "/path/to/mongodb_resume_token"
    mappings:
      - source_database: "source_db_1"
        target_database: "target_db_1"
        tables:
          - source_table: "source_table_1"
            target_table: "target_table_1"
          - source_table: "source_table_2"
            target_table: "target_table_2"

  - type: "mysql"
    enable: true
    source_connection: "<source_username>:<source_password>@tcp(<source_host>:<source_port>)/<source_database>"
    target_connection: "<target_username>:<target_password>@tcp(<target_host>:<target_port>)/<target_database>"
    mysql_position_path: "/path/to/mysql_position"
    mappings:
      - source_database: "source_db_1"
        target_database: "target_db_1"
        tables:
          - source_table: "source_table_1"
            target_table: "target_table_1"
          - source_table: "source_table_2"
            target_table: "target_table_2"
    dump_execution_path: "" # optional

  - type: "mariadb"
    enable: true
    source_connection: "<source_username>:<source_password>@tcp(<mariadb_source_host>:<mariadb_source_port>)/<source_database>"
    target_connection: "<target_username>:<target_password>@tcp(<mariadb_target_host>:<mariadb_target_port>)/<target_database>"
    mysql_position_path: "/path/to/mariadb_position"
    mappings:
      - source_database: "source_db_1"
        target_database: "target_db_1"
        tables:
          - source_table: "source_table_1"
            target_table: "target_table_1"
          - source_table: "source_table_2"
            target_table: "target_table_2"
    dump_execution_path: "/path/to/dump_tool"

  - type: "postgresql"
    enable: true
    source_connection: "postgres://<source_username>:<source_password>@<pg_source_host>:<pg_source_port>/<source_db>?sslmode=disable"
    target_connection: "postgres://<target_username>:<target_password>@<pg_target_host>:<pg_target_port>/<target_db>?sslmode=disable"
    pg_position_path: "/path/to/postgresql_position"
    pg_replication_slot: "sync_slot"
    pg_plugin: "wal2json"
    mappings:
      - source_database: "source_db_1"
        target_database: "target_db_1"
        tables:
          - source_table: "source_table_1"
            target_table: "target_table_1"
          - source_table: "source_table_2"
            target_table: "target_table_2"   